### PR TITLE
add creativecommon license

### PR DESCRIPTION
**Pull request by suchov**
https://creativecommons.org/publicdomain/zero/1.0/
I think this type of license fits us.
@sudodoki what do you think?

### CODE REVIEW

**Comment by sudodoki** [comment]
I would suggest @xanf take a look at this. Generally, LGTM.

**Comment by suchov** [comment]
@xanf ^

**Comment by xanf** [comment]
I'm not really sure absolute zero license is the best fit (maybe I'm too greedy ;) )

My suggestion is: 

https://creativecommons.org/licenses/by/3.0/

**Comment by suchov** [comment]
ok @xanf I'll change it to 3.0 and merge then

**Comment by suchov** [comment]
@xanf and what about now? I just want to create the common one to copy it to all Kottans repos

**Pull request merged**
